: EVENTUALLY-DELIVERED-CLAIM?  ( assumptions -- flag )  EVENTUAL-DELIVERY-FOR-RETAINED-EXPORT? NO-PERMANENT-TARGET-UNAVAILABILITY? AND ;
: EVENTUALLY-OBSERVED-CLAIM?   ( assumptions -- flag )  EVENTUAL-DELIVERY-FOR-RETAINED-EXPORT? EVENTUAL-TARGET-OBSERVATION? NO-PERMANENT-TARGET-UNAVAILABILITY? AND AND ;
: EVENTUALLY-RESOLVED-CLAIM?   ( assumptions -- flag )  EVENTUAL-DELIVERY-FOR-RETAINED-EXPORT? EVENTUAL-TARGET-OBSERVATION? TARGET-LOCAL-SEED-EVENTUAL-RESOLUTION? NO-PERMANENT-TARGET-UNAVAILABILITY? AND AND AND ;
: RESOLVED-RESULT-PERMITTED?   ( result -- flag )       SEED-TERMINAL-RESULT? ;
