from __future__ import annotations

import json
import re
import shutil
from pathlib import Path
from typing import Any

from tools.alpha4_network_seed_extension import (
    check_seed_companion_bases,
    parse_seed_binding,
    sha256,
)

ROOT = Path(__file__).resolve().parents[1]

SUBJECT_MANIFESTS = (
    ("NETWORK", "network/alpha4/NETWORK.aset"),
    ("DYNAMIC", "network/alpha4/profiles/dynamic/DYNAMIC.aset"),
    ("FEDERATION", "network/alpha4/profiles/federation/FEDERATION.aset"),
    ("LIVENESS", "network/alpha4/profiles/liveness/LIVENESS.aset"),
    (
        "FEDERATION-LIVENESS",
        "network/alpha4/profiles/composition/federation-liveness/FEDERATION_LIVENESS.aset",
    ),
)


class ReleaseProfileError(RuntimeError):
    pass


def require(condition: bool, message: str) -> None:
    if not condition:
        raise ReleaseProfileError(message)


def _manifest_records(root: Path = ROOT) -> list[dict[str, str]]:
    records: list[dict[str, str]] = []
    for subject, relative in SUBJECT_MANIFESTS:
        lines = [
            line.strip()
            for line in (root / relative).read_text(encoding="utf-8").splitlines()
            if line.strip()
        ]
        causal = {}
        for line in lines:
            if line.startswith("CAUSAL-BIND "):
                _, component_id, causal_transition = line.split()
                causal[component_id] = causal_transition
        for line in lines:
            if not line.startswith("PAIR "):
                continue
            parts = line.split()
            require(len(parts) == 6, f"bad PAIR declaration in {relative}: {line}")
            _, component_id, transition_binding, relational, _reflection, pairing = parts
            require(component_id in causal, f"causal binding missing for {component_id}")
            operational = transition_binding
            if subject == "NETWORK":
                operational = {
                    "ASET-NETWORK-COMPONENT-ADMIT-FRESH": "ADMIT-FRESH",
                    "ASET-NETWORK-COMPONENT-ADMIT-REPLAY": "ADMIT-REPLAY",
                    "ASET-NETWORK-COMPONENT-REJECT-CONFLICT": "REJECT-CONFLICT",
                }[component_id]
            seed_extension = "NONE"
            if subject == "NETWORK" and component_id in {
                "ASET-NETWORK-COMPONENT-ADMIT-FRESH",
                "ASET-NETWORK-COMPONENT-ADMIT-REPLAY",
            }:
                seed_extension = "OBSERVE-UNKNOWN"
            records.append(
                {
                    "subject": subject,
                    "component_id": component_id,
                    "transition_binding": transition_binding,
                    "operational": operational,
                    "relational": relational,
                    "causal": causal[component_id],
                    "pairing": pairing,
                    "seed_extension": seed_extension,
                }
            )
    return records


def write_english(target: Path, seed_english_sha256: str, records: list[dict[str, str]]) -> None:
    lines = [
        "# ASET Network 0.1.0-alpha.4 — generated release companion extension",
        "",
        "Generated by release CI. Semantic precedence: none.",
        f"Exact Seed English base SHA-256: `{seed_english_sha256}`",
        "",
        (
            "This document adds only Network-owned expression content; "
            "the Seed companion remains the exact base expression."
        ),
        "",
    ]
    for item in records:
        lines += [
            f"### {item['component_id']}",
            f"Subject: `{item['subject']}`",
            f"Transition: `{item['transition_binding']}`",
            f"Operational: `{item['operational']}`",
            f"Relational: `{item['relational']}`",
            f"Causal: `{item['causal']}`",
            f"Seed extension: `{item['seed_extension']}`",
            "",
        ]
    target.write_text("\n".join(lines), encoding="utf-8")


def parse_english(path: Path) -> list[dict[str, str]]:
    text = path.read_text(encoding="utf-8")
    sections = re.split(r"(?m)^### ", text)[1:]
    records: list[dict[str, str]] = []
    for section in sections:
        lines = [line.strip() for line in section.splitlines() if line.strip()]
        component_id = lines[0]
        fields: dict[str, str] = {}
        for line in lines[1:]:
            match = re.fullmatch(r"([A-Za-z ]+): `(.*)`", line)
            if match:
                fields[match.group(1)] = match.group(2)
        records.append(
            {
                "subject": fields["Subject"],
                "component_id": component_id,
                "transition_binding": fields["Transition"],
                "operational": fields["Operational"],
                "relational": fields["Relational"],
                "causal": fields["Causal"],
                "seed_extension": fields["Seed extension"],
            }
        )
    return records


def write_python(target: Path, seed_python_sha256: str, records: list[dict[str, str]]) -> None:
    metadata = json.dumps(records, indent=2, sort_keys=True)
    text = f'''"""Generated ASET Network 0.1.0-alpha.4 Python companion extension.

The exact ASET Seed Python companion is the base expression. Semantic precedence: none.
"""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Any

BASE_SEED_EXPRESSION_SHA256 = {seed_python_sha256!r}
BASE_SEED_EXPRESSION_PATH = (
    Path(__file__).resolve().parents[1]
    / "base"
    / "seed"
    / "python"
    / "aset_seed_alpha4.py"
)
COMPONENT_BINDINGS = {metadata}


def _sha256(path: Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def _load_seed_base() -> dict[str, Any]:
    if _sha256(BASE_SEED_EXPRESSION_PATH) != BASE_SEED_EXPRESSION_SHA256:
        raise RuntimeError("exact Seed Python companion byte identity mismatch")
    namespace: dict[str, Any] = {{}}
    source = BASE_SEED_EXPRESSION_PATH.read_text(encoding="utf-8")
    exec(compile(source, str(BASE_SEED_EXPRESSION_PATH), "exec"), namespace)
    return namespace


_seed = _load_seed_base()


def _exact_observation(value: dict[str, Any]) -> bool:
    fields = {{"import_id", "source_context", "target_context", "evidence_digest"}}
    if set(value) != fields:
        return False
    if not all(isinstance(value[key], str) and value[key] for key in fields):
        return False
    digest = value["evidence_digest"]
    return (
        isinstance(digest, str)
        and len(digest) == 71
        and digest.startswith("sha256:")
        and all(ch in "0123456789abcdef" for ch in digest[7:])
    )


def _network_result(accepted: bool, code: str, changed: bool) -> dict[str, Any]:
    return {{
        "accepted": accepted,
        "code": code,
        "state_changed": changed,
        "seed_projection": {{
            "component": "ASET-COMPONENT-OBSERVE-UNKNOWN" if accepted else None,
            "recognition": "UNKNOWN" if accepted else "NOT_APPLICABLE",
            "effect_permitted": False,
        }},
    }}


def admit_import(
    imports: list[dict[str, Any]],
    observation: dict[str, Any],
    seed_state: dict[str, Any],
) -> tuple[list[dict[str, Any]], dict[str, Any], dict[str, Any]]:
    current_imports = [dict(item) for item in imports]
    current_seed = dict(seed_state)
    if not _exact_observation(observation):
        raise ValueError("exact import observation required")
    same_id = [item for item in current_imports if item["import_id"] == observation["import_id"]]
    if observation in same_id:
        next_imports = current_imports
        result = _network_result(True, "IDEMPOTENT_REPLAY", False)
    elif same_id:
        return current_imports, current_seed, _network_result(False, "IDENTIFIER_CONFLICT", False)
    else:
        next_imports = [*current_imports, dict(observation)]
        result = _network_result(True, "IMPORT_ADMITTED", True)
    next_seed = _seed["apply_component"](
        current_seed,
        "ASET-COMPONENT-OBSERVE-UNKNOWN",
        evidence=observation["evidence_digest"],
    )
    return next_imports, next_seed, result


def profile_applicable(exact_binding: bool, recognition: str) -> bool:
    return exact_binding and recognition == "ALLOW"


def profile_network_stutter(before: Any, after: Any) -> bool:
    return before == after


LIVENESS_REQUIRED = {{
    "EVENTUAL_DELIVERY_FOR_RETAINED_EXPORT",
    "EVENTUAL_TARGET_OBSERVATION",
    "TARGET_LOCAL_SEED_EVENTUAL_RESOLUTION",
    "NO_PERMANENT_TARGET_UNAVAILABILITY",
}}


def eventually_delivered_claim(assumptions: set[str]) -> bool:
    return {{
        "EVENTUAL_DELIVERY_FOR_RETAINED_EXPORT",
        "NO_PERMANENT_TARGET_UNAVAILABILITY",
    }} <= assumptions


def eventually_observed_claim(assumptions: set[str]) -> bool:
    return {{
        "EVENTUAL_DELIVERY_FOR_RETAINED_EXPORT",
        "EVENTUAL_TARGET_OBSERVATION",
        "NO_PERMANENT_TARGET_UNAVAILABILITY",
    }} <= assumptions


def eventually_resolved_claim(assumptions: set[str]) -> bool:
    return LIVENESS_REQUIRED <= assumptions


def resolved_result_permitted(result: str) -> bool:
    return result in {{"ALLOW", "BLOCK"}}


REQUIRED_CAPABILITIES = {{"RETAINED_EXPORT", "DELIVERY", "TARGET_OBSERVATION"}}


def required_capabilities_satisfied(provided: set[str]) -> bool:
    return REQUIRED_CAPABILITIES <= provided


def composition_boundary_preserved(
    parent_relation: bool,
    state_transfer: bool,
    transition_transfer: bool,
    authority_transfer: bool,
) -> bool:
    return not any((parent_relation, state_transfer, transition_transfer, authority_transfer))


def delivery_witness(exported: set[str], delivered: set[str], export: str) -> bool:
    return export in exported and export in delivered


def observation_witness(delivered: set[str], observed: set[str], export: str) -> bool:
    return export in delivered and export in observed


def resolution_witness(observed: set[str], resolved: set[str], export: str) -> bool:
    return export in observed and export in resolved


def progress_witness(
    exported: set[str],
    delivered: set[str],
    observed: set[str],
    resolved: set[str],
    export: str,
) -> bool:
    return (
        delivery_witness(exported, delivered, export)
        and observation_witness(delivered, observed, export)
        and resolution_witness(observed, resolved, export)
    )


def federation_state() -> dict[str, Any]:
    return {{
        "federation_id": None,
        "federation_epoch": None,
        "members": {{}},
        "routes": {{}},
        "exports": frozenset(),
    }}


def _copy_federation(state: dict[str, Any]) -> dict[str, Any]:
    return {{
        "federation_id": state["federation_id"],
        "federation_epoch": state["federation_epoch"],
        "members": dict(state["members"]),
        "routes": dict(state["routes"]),
        "exports": frozenset(state["exports"]),
    }}


def federation_genesis(state: dict[str, Any], federation_id: str, epoch: str) -> dict[str, Any]:
    if state["federation_id"] is not None or state["federation_epoch"] is not None:
        raise ValueError("federation already exists")
    if state["members"] or state["routes"] or state["exports"]:
        raise ValueError("federation genesis requires empty state")
    result = _copy_federation(state)
    result["federation_id"] = federation_id
    result["federation_epoch"] = epoch
    return result


def member_join(state: dict[str, Any], context: str) -> dict[str, Any]:
    if state["federation_id"] is None:
        raise ValueError("federation missing")
    if state["members"].get(context, "ABSENT") != "ABSENT":
        raise ValueError("member is not absent")
    result = _copy_federation(state)
    result["members"][context] = "ACTIVE"
    return result


def route_grant(state: dict[str, Any], source: str, target: str) -> dict[str, Any]:
    route = (source, target)
    if source == target:
        raise ValueError("route endpoints must be distinct")
    if state["members"].get(source) != "ACTIVE" or state["members"].get(target) != "ACTIVE":
        raise ValueError("route endpoints must be active")
    if state["routes"].get(route, "ABSENT") != "ABSENT":
        raise ValueError("route is not absent")
    result = _copy_federation(state)
    result["routes"][route] = "ACTIVE"
    return result


def export_artifact(
    state: dict[str, Any], source: str, target: str, artifact: str
) -> dict[str, Any]:
    route = (source, target)
    export = (source, target, artifact)
    if state["routes"].get(route) != "ACTIVE":
        raise ValueError("route is not active")
    if export in state["exports"]:
        raise ValueError("export already exists")
    result = _copy_federation(state)
    result["exports"] = frozenset((*state["exports"], export))
    return result


def suspend_route(state: dict[str, Any], source: str, target: str) -> dict[str, Any]:
    route = (source, target)
    if state["routes"].get(route) != "ACTIVE":
        raise ValueError("route is not active")
    result = _copy_federation(state)
    result["routes"][route] = "SUSPENDED"
    return result


def member_withdraw(state: dict[str, Any], context: str) -> dict[str, Any]:
    if state["members"].get(context) != "ACTIVE":
        raise ValueError("member is not active")
    for (source, target), route_state in state["routes"].items():
        if route_state == "ACTIVE" and context in {{source, target}}:
            raise ValueError("active route prevents withdrawal")
    result = _copy_federation(state)
    result["members"][context] = "WITHDRAWN"
    return result
'''
    target.write_text(text, encoding="utf-8")


def build_release_profiles(seed_profiles_root: Path, output: Path) -> dict[str, Any]:
    binding = parse_seed_binding()
    seed_evidence = check_seed_companion_bases(seed_profiles_root)
    if output.exists():
        shutil.rmtree(output)
    (output / "base/seed/en").mkdir(parents=True)
    (output / "base/seed/python").mkdir(parents=True)
    (output / "en").mkdir(parents=True)
    (output / "python").mkdir(parents=True)

    seed_english_rel, seed_english_sha = binding.companions["ENGLISH"]
    seed_python_rel, seed_python_sha = binding.companions["PYTHON"]
    seed_english_target = output / "base/seed/en/Seed.md"
    seed_python_target = output / "base/seed/python/aset_seed_alpha4.py"
    shutil.copy2(seed_profiles_root / seed_english_rel, seed_english_target)
    shutil.copy2(seed_profiles_root / seed_python_rel, seed_python_target)
    require(sha256(seed_english_target) == seed_english_sha, "copied Seed English base drift")
    require(sha256(seed_python_target) == seed_python_sha, "copied Seed Python base drift")

    records = _manifest_records(ROOT)
    english = output / "en/Network.md"
    python = output / "python/aset_network_alpha4.py"
    write_english(english, seed_english_sha, records)
    write_python(python, seed_python_sha, records)

    parsed = parse_english(english)
    expected = [
        {
            key: item[key]
            for key in (
                "subject",
                "component_id",
                "transition_binding",
                "operational",
                "relational",
                "causal",
                "seed_extension",
            )
        }
        for item in records
    ]
    require(parsed == expected, "Network controlled English round-trip mismatch")

    return {
        "document_type": "aset-network-release-companion-evidence",
        "semantic_precedence": "NONE",
        "relation": "EXTENSION_OF_EXACT_SEED_COMPANIONS",
        "seed_profile_tree_digest": seed_evidence["profile_tree_digest"],
        "base_expressions": {
            "english": {"path": "base/seed/en/Seed.md", "sha256": seed_english_sha},
            "python": {"path": "base/seed/python/aset_seed_alpha4.py", "sha256": seed_python_sha},
        },
        "network_expressions": {
            "english": {"path": "en/Network.md", "sha256": sha256(english)},
            "python": {"path": "python/aset_network_alpha4.py", "sha256": sha256(python)},
        },
        "english_components_checked": len(records),
        "status": "PASS",
    }


if __name__ == "__main__":
    raise SystemExit("use build_alpha4_network_release.py")
